---
- name: Registering Instance PVM AMI to snapshot
  shell: 'aws ec2 register-image --output text --image-location {{ ami_bundle_bucket_path }}/{{ buri_ami_full_name }}/{{ buri_ami_full_name }}.img.manifest.xml  --name "{{ buri_ami_full_name }}-PVM-S3-{{ buri_disk_type }}" --description "{{ buri_ami_description }}" --kernel-id "{{ ami_aki_id }}" --region {{ ansible_ec2_placement_region }}'
  register: amipvminstance

- name: Saving Instance PVM AMI ID as a fact for later use
  set_fact:
    ami_id_pvm_instance: '{{ amipvminstance.stdout }}'

- include: tasks/ec2/ami/tag/common.yml
  vars:
    tag_ami_id: '{{ ami_id_pvm_instance }}'
    tag_ami_name: '{{ buri_ami_full_name }}-PVM-S3-{{ buri_disk_type }}'

