---
# Asgard role
- name: Copy tomcat server.xml file
  copy: src=server.xml dest=/usr/local/tomcat/conf/server.xml owner=root group=root mode=0644
  notify: restart webapps container
  when: servlet_container == "tomcat"

- name: Copy over tomcat-users.xml file
  template: src=tomcat-users.xml dest=/usr/local/tomcat/conf/tomcat-users.xml owner=root group=root mode=0644
  notify: restart webapps container
  when: servlet_container == "tomcat"

- name: Create Asgard Home at /usr/share/tomcat7/.asgard
  file: path=/usr/share/tomcat7/.asgard state=directory owner={{ tomcat_user }}  group={{ tomcat_user }}  mode=0755
  when: servlet_container == "tomcat"

- name: Copy jetty app context xml file
  copy: src=asgard.xml dest={{ webapps_root }}/root.xml owner={{ jetty_user }} group={{ jetty_group }} mode=0644
  notify: restart webapps container
  when: servlet_container == "jetty9"

- name: Copy jetty realm.properties file
  template: src=realm.properties dest={{ jetty_app_root}}/etc/ owner={{ jetty_user }} group={{ jetty_group }} mode=0644
  notify: restart webapps container
  when: servlet_container == "jetty9"

- name: Download build of Asgard from Github
  get_url: url={{ asgard_build_url }} dest=/tmp/asgard.war
  
- name: Remove any old version
  file: path={{ webapps_root }}/ROOT state=absent
  
- name: Create Asgard deployment directory
  file: path={{ webapps_root }}/ROOT state=directory

- name: Decompress Asgard WAR file
  command: chdir={{ webapps_root }}/ROOT unzip /tmp/asgard.war
  notify: restart webapps container
  
- name: Remove source WAR file
  file: path=/tmp/asgard.war state=absent

- name: Add BASIC auth requirements to web.xml
  lineinfile: dest={{ webapps_root }}/ROOT/WEB-INF/web.xml regexp="security-constraint" line="<security-constraint><web-resource-collection><web-resource-name></web-resource-name><url-pattern>/*</url-pattern></web-resource-collection><auth-constraint><role-name>asgard</role-name></auth-constraint></security-constraint><login-config><auth-method>BASIC</auth-method><realm-name>asgard</realm-name></login-config>" insertbefore="</web-app>"
  notify: restart webapps container
   
