---
# Asgard role
- name: Copy jetty app context xml file
  copy: src=asgard.xml dest={{ asgard_webapps_root }}/ROOT.xml owner={{ jetty_user }} group={{ jetty_group }} mode=0644
  notify: restart asgard
  when: servlet_container == "jetty9"

- name: Copy jetty realm.properties file
  template: src=realm.properties dest={{ jetty_apps }}/{{ asgard_instance_name }}/etc/ owner={{ jetty_user }} group={{ jetty_group }} mode=0644
  notify: restart asgard
  when: servlet_container == "jetty9"

- include: acquire_build.yml

- name: Remove any old version
  file: path={{ asgard_webapps_root }}/ROOT state=absent
  
- name: Create Asgard deployment directory
  file: path={{ asgard_webapps_root }}/ROOT state=directory

- name: Decompress Asgard WAR file
  command: chdir={{ asgard_webapps_root }}/ROOT jar xf /tmp/asgard.war
  notify: restart asgard
  
- name: Remove source WAR file
  file: path=/tmp/asgard.war state=absent

- name: Add ASGARD_HOME to runtime environment
  lineinfile: dest=/etc/default/jetty-{{ asgard_instance_name }} regexp="ASGARD_HOME" line="ASGARD_HOME=/opt/asgard" insertafter="EOF"
  when: ansible_distribution == 'Ubuntu' and servlet_container == "jetty9"
  notify: restart asgard

- name: Create Asgard config directory
  file: path=/opt/asgard state=directory owner={{ servlet_container_user }} group={{ servlet_container_group }} mode=0755

- name: Generate Config.groovy file for Asgard
  template: src=Config.groovy dest=/opt/asgard/Config.groovy owner={{ servlet_container_user }} group={{ servlet_container_user }} mode=0644

- name: Add BASIC auth requirements to web.xml
  lineinfile: dest={{ asgard_webapps_root }}/ROOT/WEB-INF/web.xml regexp="security-constraint" line="<security-constraint><web-resource-collection><web-resource-name></web-resource-name><url-pattern>/*</url-pattern></web-resource-collection><auth-constraint><role-name>asgard</role-name></auth-constraint></security-constraint><login-config><auth-method>BASIC</auth-method><realm-name>asgard</realm-name></login-config>" insertbefore="</web-app>"
  notify: restart asgard
   
