---
- name: restart turbine
  shell: ( status jetty-instance INAME={{ turbine_instance_name }} && stop jetty-instance INAME={{ turbine_instance_name }} ) ; start jetty-instance INAME={{ turbine_instance_name }}
  when: not image_build

