---
- name: restart rssdemo edge
  shell: ( status jsvc_daemon_instance INAME={{ rssdemo_edge_instance_name }} && stop jsvc_daemon_instance INAME={{ rssdemo_edge_instance_name }} ) ; start jsvc_daemon_instance INAME={{ rssdemo_edge_instance_name }}
  when: not image_build

