---
# Don't use ansible module 'mount', as this is a transient thing
- name: Creating mount point for EBS volume
  file:
    path: '{{ ami_image_mount }}'
    state: directory
    owner: root
    group: root
    mode: 0444

- name: Mount EBS volume for chroot
  command: 'mount {{ ami_device }}1 {{ ami_image_mount }}'

- name: Mount /proc filesystem into chroot
  command: 'chroot {{ ami_image_mount }} mount -t proc none /proc'

- name: Mount (bind) /dev filesystem into chroot
  command: 'mount -o bind /dev {{ ami_image_mount }}/dev'

# Don't use copy action, just command cp on remote
- name: Remove resolv.conf (maybe link) from chroot environment
  command: 'rm -f {{ ami_image_mount }}/etc/resolv.conf'

- name: Add working resolv.conf to chroot environment
  command: 'cp /etc/resolv.conf {{ ami_image_mount }}/etc/resolv.conf'

- name: Disable rc.d for rest of the process.
  copy:
    src: files/policy-rc.d
    dest: '{{ ami_image_mount }}/usr/sbin/policy-rc.d'
    owner: root
    group: root
    mode: 0755

