---
- name: Fetch distribution hard disk image
  get_url:
    url: '{{ distro_image_url }}'
    dest: '{{ distro_image_path }}'
    owner: 'root'
    group: 'root'
    mode: 0444

- name: Writing disk image to volume
  command: 'qemu-img convert -O host_device {{ distro_image_path }} {{ buri_disk_device }}'

- name: Scanning EBS volume for new partition table
  command: 'partprobe {{ buri_disk_device }}'

