---
- debug:
    msg: 'name:            {{ ami_name}}'
- debug:
    msg: 'description:     {{ ami_description }}'
- debug:
    msg: 'region:          {{ ansible_ec2_placement_region }} ({{ ansible_ec2_placement_availability_zone }})'
- debug:
    msg: 'Parent AMI ID:   {{ ami_parent }}'
- debug:
    msg: 'Parent EBS ID:   {{ ebs_parent_id }}'
- debug:
    msg: 'PVM AMI ID:      {{ ami_id_pvm }}'
- debug:
    msg: 'HVM AMI ID:      {{ ami_id_hvm }}'
- debug:
    msg: 'AKI ID:          {{ ami_aki_id }}'
- debug:
    msg: 'EBS volume ID:   {{ ebs_volume_id }} (deleted)'
- debug:
    msg: 'EBS snapshot ID: {{ ebs_snapshot_id }}'

