---
- name: Copy jetty app context xml file
  copy: src=edda.xml dest={{ webapps_root }}/edda.xml owner={{ jetty_user }} group={{ jetty_group }} mode=0644
  notify: restart webapps container
  when: servlet_container == "jetty9"

- name: Remove default root webapp
  file: path={{ webapps_root }}/ROOT state=absent
  notify: restart webapps container

- name: Download snapshot build of Edda from Cloudbees
  get_url: url={{ edda_build_url }} dest=/tmp/edda.war
  
- name: Remove any old version
  file: path={{ webapps_root }}/edda state=absent
  
- name: Create Edda deployment directory
  file: path={{ webapps_root }}/edda state=directory

- name: Decompress Edda WAR file
  command: chdir={{ webapps_root }}/edda unzip /tmp/edda.war
  notify: restart webapps container
  
- name: Remove source WAR file
  file: path=/tmp/edda.war state=absent
  notify: restart webapps container

- name: Copy edda.properties
  template: src=edda.properties dest={{ webapps_root }}/edda/WEB-INF/classes/edda.properties owner=root group=root mode=0644
  notify: restart webapps container

