---
# Set up package repositories
# main.yml must have a when: ansible_distribution == 'Ubuntu' on including this

- name: Ensure APT sources list includes multiverse
  copy: src={{ ansible_distribution }}/{{ ansible_distribution_release }}/sources.list dest=/etc/apt/sources.list owner=root group=root mode=0444

- debug: var=ansible_distribution_version

- name: Patch cloud-init APT sources template (old form)
  copy: src={{ ansible_distribution }}/{{ ansible_distribution_release }}/sources.list.tmpl dest=/etc/cloud/templates/sources.list.tmpl owner=root group=root mode=0444
  when: ansible_distribution_version|float < 14.04

- name: Patch cloud-init APT sources template (new form)
  copy: src={{ ansible_distribution }}/{{ ansible_distribution_release }}/sources.list.ubuntu.tmpl dest=/etc/cloud/templates/sources.list.ubuntu.tmpl owner=root group=root mode=0444
  when: ansible_distribution_version|float >= 14.04
## FIXME: boundary is after 12.04, maybe before 14.04, unconfirmed

- name: Add PPA for AWS tools backports
  apt_repository: repo='ppa:jhohertz/aws-ppa'
  when: ansible_distribution_version|float == 12.04
## FIXME: we only have PPAs for 12.04 right now

- name: Update APT repo information
  apt: update-cache=yes

# Upgrade/install packages

- name: Upgrade APT packages to current
  apt: upgrade=dist

- name: Install build dependencies
  apt: pkg={{ item }} state=latest install_recommends=no
  with_items:
    - coreutils
    - ec2-ami-tools
    - ec2-api-tools
    - python
    - python-support
    - python-pip
    - python-crypto
    - python-jinja2
    - libapt-pkg4.12
    - make
    - qemu-utils
    - git-core
    - ansible

- name: Install boto Python library
  pip: name=boto state=latest

- name: Install AWS CLI
  pip: name=awscli state=latest


