---
dependencies:
  - { role: jetty9_instance, jetty_instance_name: '{{ turbine_instance_name }}', jetty_instance_port: '{{ turbine_instance_port }}', jetty_jvm_extra_opts: '{{ turbine_jvm_extra_opts }}' }
