---
- name: restart exhibitor
  shell: ( status jetty-instance INAME={{ exhibitor_instance_name }} && stop jetty-instance INAME={{ exhibitor_instance_name }} ) ; start jetty-instance INAME={{ exhibitor_instance_name }}
  when: not image_build

