---
cassandra_nameprefix: "apache-cassandra"
cassandra_version: "2.0.10"
#cassandra_mirror: "http://downloads.datastax.com/community/{{ cassandra_nameprefix }}-{{ cassandra_version }}-bin.tar.gz"
cassandra_build_url: "http://apache.mirror.iweb.ca/cassandra/{{ cassandra_version }}/{{ cassandra_nameprefix }}-{{ cassandra_version }}-bin.tar.gz"
cassandra_checksum: "962ab35b1767ed4c56eb9a2a6b9df374097dc48d4f1c718945cab3a977e5d9fa"

cassandra_build_source: False
# this one's really slow? also a mirror
#cassandra_git_repo: https://github.com/apache/cassandra.git
cassandra_git_repo: http://git-wip-us.apache.org/repos/asf/cassandra.git
cassandra_git_ref: cassandra-2.0

cassandra_user: "cassandra"
cassandra_group: "cassandra"
cassandra_home: "/opt/cassandra"
cassandra_installdir: "/opt/{{ cassandra_nameprefix }}-{{ cassandra_version }}"
cassandra_base_location: "/mnt/cassandra"
cassandra_log_location: "/var/log/cassandra"
cassandra_data_location: "/mnt/cassandra/data"
cassandra_cache_location: "/mnt/cassandra/saved_caches"
cassandra_commitlog_location: "/mnt/cassandra/commitlog"

cassandra_partitioner: "org.apache.cassandra.dht.RandomPartitioner"
cassandra_rpc_server_type: "hsha"
cassandra_stream_throughput: 400
cassandra_index_interval: 256

# overridden by priam to add extension
cassandra_jvm_opts: ""

