---
cassandra_nameprefix: "apache-cassandra"
cassandra_version: "1.2.18"
#cassandra_mirror: "http://downloads.datastax.com/community/{{ cassandra_nameprefix }}-{{ cassandra_version }}-bin.tar.gz"
cassandra_mirror: "http://apache.mirror.iweb.ca/cassandra/{{ cassandra_version }}/{{ cassandra_nameprefix }}-{{ cassandra_version }}-bin.tar.gz"
cassandra_checksum: "7f76aca107b8674d370bf4c37815027dd0d30e8f6e57b7471e050201729ddb92"

cassandra_user: "cassandra"
cassandra_group: "cassandra"
cassandra_home: "/opt/cassandra"
cassandra_installdir: "/opt/{{ cassandra_nameprefix }}-{{ cassandra_version }}"
cassandra_base_location: "/mnt/cassandra"
cassandra_log_location: "/var/log/cassandra"
cassandra_data_location: "/mnt/cassandra/data"
cassandra_cache_location: "/mnt/cassandra/saved_caches"
cassandra_commitlog_location: "/mnt/cassandra/commitlog"

# overridden by priam to add extension
cassandra_jvm_opts: ""

