---
# Ice role
- name: Copy tomcat server.xml file
  copy: src=server.xml dest=/usr/local/tomcat/conf/server.xml owner=root group=root mode=0644
  notify: restart webapps container
  when: servlet_container == "tomcat"

- name: Copy jetty app context xml file
  copy: src=ice.xml dest={{ webapps_root }}/ice.xml owner={{ jetty_user }} group={{ jetty_group }} mode=0644
  notify: restart webapps container
  when: servlet_container == "jetty9"


- name: Remove default root webapp
  file: path={{ webapps_root }}/ROOT state=absent
  notify: restart webapps container

- name: Download snapshot build of Ice from Cloudbees
  get_url: url={{ ice_build_url }} dest=/tmp/ice.war
  
- name: Remove any old version
  file: path={{ webapps_root }}/ice state=absent
  
- name: Create Ice deployment directory
  file: path={{ webapps_root }}/ice state=directory

- name: Decompress Ice WAR file
  command: chdir={{ webapps_root }}/ice unzip /tmp/ice.war
  notify: restart webapps container
  
- name: Remove source WAR file
  file: path=/tmp/ice.war state=absent
  notify: restart webapps container

- name: Copy ice.properties
  template: src=ice.properties.j2 dest={{ webapps_root }}/ice/WEB-INF/classes/ice.properties owner=root group=root mode=0644
  notify: restart webapps container
  
- name: Add ICE_HOME to environment (tomcat)
  lineinfile: dest=/etc/default/tomcat7 regexp="ICE_HOME" line="ICE_HOME={{ webapps_root }}/ice/WEB-INF/classes/"
  when: ansible_distribution == 'Ubuntu' and servlet_container == "tomcat"
  notify: restart webapps container

- name: Add ICE_HOME to environment (jetty)
  lineinfile: dest=/etc/default/jetty regexp="ICE_HOME" line="ICE_HOME={{ webapps_root }}/ice/WEB-INF/classes/"
  when: ansible_distribution == 'Ubuntu' and servlet_container == "jetty9"
  notify: restart webapps container

- name: Adding ephemeral_dirs spec for ice
  template: src=ephemeral-dirs dest=/etc/ephemeral-dirs owner=root group=root mode=0644
   
