---
jetty_version: '9.2.6.v20141205'
jetty_basename: 'jetty-distribution-{{ jetty_version }}'
jetty_filename: '{{ jetty_basename }}.tar.gz'
jetty_mirror: 'http://mirror.csclub.uwaterloo.ca/eclipse/jetty/{{ jetty_version }}/dist/{{ jetty_filename }}'
jetty_checksum: '94dc77852f07bee06ac97c7ea845e5ecf175d55eb55bc02a8b0b80529285994d'
jetty_root: '/opt/jetty'
jetty_temp: '{{ jetty_root }}/temp'
jetty_apps: '{{ jetty_root }}/apps'
jetty_install_dir: '{{ jetty_root }}/{{ jetty_basename }}'
jetty_user: 'jetty'
jetty_group: 'jetty'
# Used as generics for container user elsewhere, and switching behavior based on containers
servlet_container: 'jetty9'
servlet_container_user: '{{ jetty_user }}'
servlet_container_group: '{{ jetty_group }}'
