---
- name: Copy jetty app context xml file
  copy: src=fluxdemo_edge.xml dest={{ fluxdemo_edge_webapps_root }}/root.xml owner={{ jetty_user }} group={{ jetty_group }} mode=0644
  notify: restart fluxdemo edge
  when: servlet_container == "jetty9"

- include: acquire_build.yml

- name: Remove any old version
  file: path={{ fluxdemo_edge_webapps_root }}/root state=absent
  
- name: Create fluxdemo_edge deployment directory
  file: path={{ fluxdemo_edge_webapps_root }}/root state=directory

- name: Decompress fluxdemo_edge WAR file
  command: chdir={{ fluxdemo_edge_webapps_root }}/root jar xf /tmp/fluxdemo_edge.war
  notify: restart fluxdemo edge
  
- name: Remove source WAR file
  file: path=/tmp/fluxdemo_edge.war state=absent
  notify: restart fluxdemo edge

- name: Copy edge.properties
  template: src=edge.properties dest={{ fluxdemo_edge_webapps_root }}/root/WEB-INF/classes/edge.properties owner={{ servlet_container_user }} group={{ servlet_container_group }} mode=0644

- name: Copy log4j.properties
  template: src=log4j.properties dest={{ fluxdemo_edge_webapps_root }}/root/WEB-INF/classes/log4j.properties owner={{ servlet_container_user }} group={{ servlet_container_group }} mode=0644

