---
- name: Create jetty root install directory
  file: path={{ jetty_root }} state=directory owner=root group=root mode=0755

- name: Add group jetty
  group: name={{ jetty_group }} system=yes

- name: Add user jetty
  user: name={{ jetty_user }} group={{ jetty_group }} shell="/bin/false" home={{ jetty_temp }} system=yes

- name: Create jetty apps root directory
  file: path={{ jetty_apps }} state=directory owner={{ jetty_user }} group={{ jetty_group }} mode=0755

- name: Create jetty root temp directory
  file: path={{ jetty_temp }} state=directory owner={{ jetty_user }} group={{ jetty_group }} mode=0755

- name: Download jetty release archive
  get_url: url={{ jetty_mirror }} dest=/tmp/{{ jetty_filename }} sha256sum={{ jetty_checksum }} owner=root mode=0644

- name: Extract jetty release archive to install dir
  command: tar -C {{ jetty_root }} -zxf /tmp/{{ jetty_filename }}

- name: Set ownership of installed release archive
  file: path={{ jetty_root }} state=directory recurse=yes owner={{ jetty_user }} group={{ jetty_group }}

- name: Install jetty upstart script
  copy: src=jetty.conf dest=/etc/init/ owner=root group=root mode=0644

