---
rssdemo_edge_instance_name: rssdemo_edge
rssdemo_edge_instance_classname: com.netflix.recipes.rss.server.EdgeServer
rssdemo_edge_instance_port: 8298
rssdemo_edge_instance_jmx_port: 7298
rssdemo_edge_instance_karyon_port: 9298
rssdemo_edge_instance_eureka_port: 8400
rssdemo_edge_jvm_xmx: '512m'
rssdemo_edge_jvm_extra_opts: ''

rssdemo_edge_app_root: '{{ jsvc_daemon_root }}/{{ rssdemo_edge_instance_name }}'
rssdemo_edge_build_url: http://slash-etc.com/java/rss-edge-0.1.0-SNAPSHOT.jar

rssdemo_edge_build_source: True
rssdemo_edge_git_repo: https://github.com/Netflix/recipes-rss.git
rssdemo_edge_git_ref: master

