---

"r3-large": {
  "mem": 10410
  },

"r3-xlarge": {
  "mem": 20821
  },

"r3-2xlarge": {
  "mem": 41642
  },

"r3-4xlarge": {
  "mem": 83285
  },

"r3-8xlarge": {
  "mem": 166570
  },

memcache_max_memory: "{{ {{ instance_type }}.mem }}"
