---
- name: restart edda
  shell: ( status jetty-instance INAME={{ edda_instance_name }} && stop jetty-instance INAME={{ edda_instance_name }} ) ; start jetty-instance INAME={{ edda_instance_name }}
  when: not image_build

