---
priam_cass_nameprefix: "dsc-cassandra"
priam_cass_version: "1.2.10"
priam_cass_mirror: "http://downloads.datastax.com/community/{{ priam_cass_nameprefix }}-{{ priam_cass_version }}-bin.tar.gz"
priam_cass_checksum: "c731c8e2bc84769f884f423fb839ab3205279972b842ab37fdace49ef511e544"
priam_version: "1.2.17"
priam_mirror: "http://dl.imedidata.net/cassandra/priam/{{ priam_version }}/priam-web-{{ priam_version }}.war"
priam_checksum: "fbc1779f9cff9a8e3a4933000a9f2784c2037519f0e1f2777ae39dfee9d831a0"
priam_ext_mirror: "http://dl.imedidata.net/cassandra/priam/{{ priam_version }}/priam-cass-extensions-{{ priam_version }}.jar"
priam_ext_checksum: "f5cbee81dd885d07c5e3aff9b45de5a8cf9674eecc4a8af0bcd736a9c86afdab"

cassandra_user: "cassandra"
cassandra_home: "/opt/cassandra"
cassandra_installdir: "/opt/{{ priam_cass_nameprefix }}-{{ priam_cass_version }}"
cassandra_base_location: "/mnt/cassandra"
cassandra_log_location: "/mnt/cassandra/logs"
cassandra_data_location: "/mnt/cassandra/data"
cassandra_cache_location: "/mnt/cassandra/saved_caches"
cassandra_commitlog_location: "/mnt/cassandra/commitlog"

