---

- name: Remove deployment keys
  file:
    path: '{{ item }}'
    state: absent
  with_items:
    - '{{ buri_ami_mount_point }}/root/.ssh/id_dsa'
    - '{{ buri_ami_mount_point }}/root/.ssh/id_rsa'

