---
- name: Unmount /proc filesystem from chroot
  command: 'chroot {{ buri_ami_mount_point }} umount /proc'

- name: Unmount /dev filesystem from chroot
  command: 'umount {{ buri_ami_mount_point }}/dev'

- name: Re-enable rc.d before snapshot
  file:
    path: '{{ buri_ami_mount_point }}/usr/sbin/policy-rc.d'
    state: absent

- name: Unmount EBS volume for chroot
  command: 'umount {{ buri_ami_mount_point }}'

- name: Removing mount point for EBS volume
  file:
    path: '{{ buri_ami_mount_point }}'
    state: absent

