riemann:
  -
    period: {{ cassandra_riemann_seconds }}
    timeunit: 'SECONDS'
    tags:
{% for tag in cassandra_riemann_tags %}
      - {{ tag }}
{% endfor %}
    hosts:
      - host: {{ cassandra_riemann_hostname }}
        port: {{ cassandra_riemann_port }}
    predicate:
      color: "white"
      useQualifiedName: true
      patterns:
        - "^java.lang.OperatingSystem.*?HeapUsage.*"
        - "^org.apache.cassandra.metrics.ThreadPools.*?Compaction.*?Pending.*"
        - '^org.apache.cassandra.metrics.ClientRequest.*?\.(Read|Write)\.Latency.*'
