---
- name: Making local image of EBS Volume to bundle
  # Before flat support, not sure qemu would know what to do with these...
  #command: 'qemu-img convert -f host_device -O raw {{ buri_disk_device }} /mnt/{{ ami_name }}.img'
  # Should work for either flat or non-flat cases
  command: 'dd if={{ buri_disk_device }} of=/mnt/{{ ami_name }}.img bs=4M'

- name: Making folder for bundle
  file:
    path: /mnt/{{ ami_name }}-bundled
    state: directory
    owner: root
    group: root
    mode: 0444

# TODO: --product-codes blabla,foo
- name: Bundling image for S3
  command: 'ec2-bundle-image -k {{ BURI_BASE }}/local/env/{{ buri_environment }}/bundle_pk.pem -c {{ BURI_BASE }}/local/env/{{ buri_environment }}/bundle_cert.pem -u {{ ami_bundle_account }} -i /mnt/{{ ami_name }}.img -d /mnt/{{ ami_name }}-bundled -r x86_64 --block-device-mapping ami=sda,root=/dev/sda1,ephemeral0=sdb'

# TODO: --region us-west-2
- name: Uploading image to S3
  command: "ec2-upload-bundle -b {{ ami_bundle_bucket_path }}/{{ ami_name }} -m /mnt/{{ ami_name }}-bundled/{{ ami_name }}.img.manifest.xml -a {{ iam_access_key }} -s {{ iam_secret_key }} -t {{ iam_token }} --retry"

- name: Removing huge temporary files for bundling to S3
  file:
    path: '{{ item }}'
    state: absent
  with_items: 
    - /mnt/{{ ami_name }}-bundled
    - /mnt/{{ ami_name }}.img
