---
# MongoDB role
- name: Install MongoDB (apt version)
  apt: pkg={{ item }} state=latest
  with_items:
    - mongodb

- name: Starting MongoDB service
  command: service mongodb start
  when: not image_build

- name: Stopping MongoDB service
  command: service mongodb stop
  when: image_build
