release_archnames:
  x86_64: "amd64"
  i386: "i386"
# Todo: factor this out via reading booted AMI for reasonable mapping
ephemeral_dev:
  x86_64: "/dev/sdb"
  i386: "/dev/sda2"
distro_name: "Ubuntu"
distro_release: "{{ ansible_distribution_release }}"
distro_version: "{{ ansible_distribution_version }}"
distro_archname: "{{ release_archnames[ansible_architecture] }}"
distro_image_basename: "{{ distro_release }}-server-cloudimg-{{ distro_archname }}"
distro_image_urlhd00: "http://uec-images.ubuntu.com/{{ distro_release }}/current/{{ distro_image_basename }}-disk1.img"
distro_image_urltar: "http://uec-images.ubuntu.com/{{ distro_release }}/current/{{ distro_image_basename }}.tar.gz"
distro_image_query: "http://uec-images.ubuntu.com/query/{{ distro_release }}/server/released.current.txt"
ami_basename: "foundation"
ami_root_size: 8
ami_root_mode: "disk"
ami_timestamp: "{{ ansible_date_time.date }}-{{ ansible_date_time.hour }}{{ ansible_date_time.minute }}"
ami_name: "{{ ami_basename }}-ubuntu-{{ distro_release }}-{{ ansible_architecture}}-{{ ami_timestamp }}"
ami_description: "{{ ami_basename }} on Ubuntu {{ distro_release }}"
ami_device_aws: "/dev/sdi"
ami_device: "/dev/xvdi"
ami_ephemeral: "{{ ephemeral_dev[ansible_architecture] }}"

