---
- name: Create jetty.base directory structure
  file: path={{ item }} state=directory owner={{ jetty_user }} group={{ jetty_group }} mode=0755
  with_items:
    - '{{ jetty_instance_root }}'
    - '{{ jetty_instance_root }}/etc'
    - '{{ jetty_instance_root }}/logs'
    - '{{ jetty_instance_root }}/resources'
    - '{{ jetty_instance_root }}/webapps'

- name: Install jetty apps start.ini file.
  copy: src=start.ini dest={{ jetty_instance_root }}/start.ini owner={{ jetty_user }} group={{ jetty_group }} mode=0644

- name: Copy jetty webdefault.xml file
  copy: src=webdefault.xml dest={{ jetty_instance_root}}/etc/webdefault.xml owner={{ jetty_user }} group={{ jetty_group }} mode=0644

- name: Copy jetty-http.xml file
  copy: src=jetty-http.xml dest={{ jetty_instance_root}}/etc/jetty-http.xml owner={{ jetty_user }} group={{ jetty_group }} mode=0644

- name: Install jetty upstart script
  copy: src=jetty.conf dest=/etc/init/ owner=root group=root mode=0644

- name: Install jetty default settings file.
  template: src=jetty-defaults dest=/etc/default/jetty owner=root group=root mode=0644

