---
- name: Disconnect, snapshot, and register newly formed AMI
  hosts: localhost
  connection: local
  sudo: True
  vars:
    image_build: true
    cloud_target: amazon
  tasks:
    - include: tasks/ec2_get_facts.yml
    - include: tasks/chroot_clean_and_unmount.yml
    - include: tasks/image_bundle_to_s3.yml
      when: ami_build_pvm_instance or ami_build_hvm_instance
    - include: tasks/ec2_ami_tag_s3_pvm.yml
      when: ami_build_pvm_instance
    - include: tasks/ec2_ami_tag_s3_hvm.yml
      when: ami_build_hvm_instance
    - include: tasks/ec2_detach_vol.yml
    - include: tasks/ec2_snapshot_vol.yml
      when: ami_build_pvm_ebs or ami_build_hvm_ebs
    - include: tasks/ec2_delete_vol.yml
    - include: tasks/ec2_ami_tag_ebs_pvm.yml
      when: ami_build_pvm_ebs
    - include: tasks/ec2_ami_tag_ebs_hvm.yml
      when: ami_build_hvm_ebs
    - include: tasks/report.yml

