---
- name: Provisioning role against chroot
  hosts: chroots
  connection: chroot
  user: root
  sudo: True
  vars_files:
    - [ "{{ BURI_BASE }}/local/env/{{ buri_environment }}/overrides.yml", "vars/dummy.yml" ]
  vars:
    image_build: true
    cloud_target: amazon
  roles:
    - "{{ ami_role }}"
