---
- name: Disconnect, snapshot, and register newly formed AMI
  hosts: localhost
  connection: local
  sudo: True
  vars:
    image_build: true
    cloud_target: amazon
  tasks:
    - include: tasks/ec2/instance/facts.yml
    - include: tasks/chroot/unmount.yml
    - include: tasks/ec2/bundle/create_and_upload.yml
      when: ami_build_pvm_instance|bool or ami_build_hvm_instance|bool
    - include: tasks/ec2/ami/tag/s3_pvm.yml
      when: ami_build_pvm_instance|bool
    - include: tasks/ec2/ami/tag/s3_hvm.yml
      when: ami_build_hvm_instance|bool
    - include: tasks/ec2/vol/detach.yml
    - include: tasks/ec2/vol/snapshot.yml
      when: ami_build_pvm_ebs|bool or ami_build_hvm_ebs|bool
    - include: tasks/ec2/vol/delete.yml
    - include: tasks/ec2/ami/tag/ebs_pvm.yml
      when: ami_build_pvm_ebs|bool
    - include: tasks/ec2/ami/tag/ebs_hvm.yml
      when: ami_build_hvm_ebs|bool
    - include: tasks/buri/report.yml

