---
- name: Provisioning role against chroot
  hosts: chroots
  connection: chroot
  user: root
  sudo: True
  vars_files:
    - [ "{{ BURI_BASE }}/local/env/{{ buri_environment }}/overrides.yml", "vars/dummy.yml" ]
  vars:
    image_build: true
    cloud_target: amazon
  tasks:
    - name: Create Buri build label folder
      file: path={{ ami_image_mount }}/var/lib/buri state=directory owner=root group=root mode=0755
    - name: Record Buri build label
      file: path={{ ami_image_mount }}/var/lib/buri/{{ ami_name }} state=touch owner=root group=root mode=0644
    - name: Record Buri cluster name
      copy: dest={{ ami_image_mount }}/var/lib/buri/cluster_name content={{ buri_cluster_name }} owner=root group=root mode=0644
  roles:
    - "{{ ami_role }}"
