---
- name: Disconnect, snapshot, and register newly formed AMI
  hosts: localhost
  connection: local
  sudo: True
  tasks:
    - include: tasks/ec2_get_facts.yml
    - include: tasks/detach_failed_vol.yml

