- name: Disconnect, snapshot, and register newly formed AMI
  hosts: localhost
  connection: local
  sudo: True
  tags: resnap
  vars:
    foo: bar
  vars_files:
    - vars/ami.yml
    - [ "vars/site.yml", "vars/site.defaults.yml" ]
  tasks:
    - include: tasks/ec2_get_facts.yml
    - include: tasks/chroot_clean_and_unmount.yml
      vars:
        chroot_mountpoint: '{{ image_mount }}'
    - include: tasks/ec2_detach_failed_vol.yml

