---
- name: Disconnect, snapshot, and register newly formed AMI
  hosts: localhost
  connection: local
  sudo: True
  vars_files:
    - [ "{{ BURI_BASE }}/local/env/{{ buri_environment }}/overrides.yml", "vars/dummy.yml" ]
  tasks:
    - include: tasks/ec2_get_facts.yml
    - include: tasks/detach_failed_vol.yml

