---
# Playbook to create a foundation snapshot/AMI from ubuntu's source images
- name: Ubuntu Foundation Create
  hosts: localhost
  connection: local
  sudo: True
  #vars:
  vars_files:
    - vars/ami.yml
    - roles/{{ ami_role }}/defaults/main.yml
    - [ "local/site.yml", "vars/site.defaults.yml" ]
  tasks:
    - include: tasks/set_build_info.yml
    - include: tasks/ec2_get_facts.yml
    - include: tasks/ec2_get_iam_info.yml
    - include: tasks/ec2_ami_find_aki_ubuntu.yml
    - include: tasks/ec2_create_vol_and_attach.yml
    - include: tasks/image_write_qcow_from_url.yml
      vars:
        image_url: '{{ distro_image_url }}'
        image_path: '{{ distro_image_path }}'
        image_device: '{{ ami_device }}'
    - include: tasks/filesystem-grow.yml
      when: ami_root_resize
    - include: tasks/chroot_mount_and_setup.yml
    - name: Register chroot target in ansible inventory
      add_host: hostname={{ ami_image_mount }} groups=chroots

- include: _image_apply_role.yml
- include: _image_finalize.yml
