---
# Playbook to create a foundation snapshot/AMI from ubuntu's source images
- name: Ubuntu Foundation Create
  hosts: localhost
  connection: local
  sudo: True
  vars_files:
    - "roles/{{ ami_role }}/defaults/main.yml"
    - [ "{{ BURI_BASE }}/local/env/{{ buri_environment }}/overrides.yml", "vars/dummy.yml" ]
  vars: 
    ami_root_resize: true
    image_build: true
  tasks:
    - name: Dump all vars
      template: src=templates/debug.j2 dest=/tmp/ansible.all
    - include: tasks/set_build_info.yml
    - include: tasks/ec2_get_facts.yml
    - include: tasks/ec2_get_iam_info.yml
    - include: tasks/ec2_ami_find_aki_ubuntu.yml
    - include: tasks/ec2_create_vol_and_attach.yml
    - include: tasks/image_create_from_tarball.yml
      when: buri_disk_type == "flat"
    - include: tasks/image_write_qcow_from_url.yml
      when: buri_disk_type != "flat"
    - name: Dump all vars
      template: src=templates/debug.j2 dest=/tmp/ansible.all2
    - include: tasks/filesystem-grow.yml 
      when: ami_root_resize and buri_disk_type != "flat"
    - include: tasks/chroot_mount_and_setup.yml
    - name: Register chroot target in ansible inventory
      add_host: hostname={{ ami_image_mount }} groups=chroots

- include: _image_apply_role.yml
- include: _image_finalize.yml
