---
# Playbook to create a foundation snapshot/AMI from ubuntu's source images
- name: Mounting EBS snapshot to work from
  hosts: localhost
  connection: local
  sudo: True
  vars_files:
    # This peeking at the role an ansible anti-pattern, more than we should need?
    # Mostly used to set cluster names for those roles using them I think
    - [ "roles/{{ ami_role }}/defaults/main.yml" ]
    - [ "{{ BURI_BASE }}/local/env/{{ buri_environment }}/overrides.yml", "vars/dummy.yml" ]
  vars:
    image_build: true
    cloud_target: amazon
    ami_root_resize: false
  tasks:
    - include: tasks/set_build_info.yml
    - include: tasks/ec2_get_facts.yml
    - include: tasks/ec2_get_iam_info.yml
    - include: tasks/ec2_ami_lookup.yml
    - include: tasks/ec2_create_vol_and_attach.yml
    - include: tasks/filesystem-grow.yml
      when: ami_root_resize and buri_disk_type != "flat" 
    - include: tasks/chroot_mount_and_setup.yml
    - name: Register chroot target in ansible inventory
      add_host: hostname={{ ami_image_mount }} groupname={{ ami_role }},chroots

- include: _image_apply_role.yml
- include: _image_finalize.yml

