---
# Playbook to create a foundation snapshot/AMI from ubuntu's source images
- name: Mounting EBS snapshot to work from
  hosts: localhost
  connection: local
  sudo: True
  #vars:
  vars_files:
    - vars/ami.yml
    - [ "local/site.yml", "vars/site.defaults.yml" ]
  tasks:
    - include: tasks/ec2_get_facts.yml
    - include: tasks/ec2_get_iam_info.yml
    - include: tasks/ec2_ami_lookup.yml
    - include: tasks/ec2_create_vol_and_attach.yml
      vars:
        ebs_size: '{{ ami_root_size }}'
        ebs_device_id: '{{ ami_device }}'
        ebs_snap: '{{ ebs_parent_id }}'
    - include: tasks/filesystem-grow.yml
      when: ami_root_resize
    - include: tasks/chroot_mount_and_setup.yml
      vars:
        chroot_mountpoint: '{{ image_mount }}'
        chroot_device: '{{ ami_device }}'
    - name: Register chroot target in ansible inventory
      add_host: hostname={{ image_mount }} groupname=chroots

- include: _image_apply_role.yml
- include: _image_finalize.yml

