---
# Playbook to create a foundation snapshot/AMI from ubuntu's source images
- name: Setup build host
  hosts: localhost
  connection: local
  sudo: True
  vars_files:
    - [ "{{ buri_environment }}/local/overrides.yml" ]
  vars:
    image_build: false
  roles:
    - build-host

