---
- name: Prepare the new EBS volume
  include: volume-prepare.yml

- name: Apply changes to chrooted AMI volume
  include: apply-chroot-changes.yml

- name: Finalize, snapshot, and register AMI
  include: volume-finalize.yml

